apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: khbgud1lg-go 
  janus-idp.io/tekton: khbgud1lg-go
  backstage.io/kubernetes-id: khbgud1lg-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: khbgud1lg-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml